#! /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python
# -*-coding: utf8-*-
# file: gallery


import os
import sys

print "********* Required Python Version:  2.7.1 *******\n"  
print "You are using Python Version: %s\n" % sys.version

MODULES_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), "python")
sys.path.insert(0, MODULES_PATH)

import utils
import gallery
path = sys.argv[-1]

print "Viewing Gallery of Path: %s\n" % path

if os.path.isdir(path):
	# pick the argumet passed
	execPath = path
else:
	# pick the current working directory
	execPath = os.getcwd()
	print "Current Working Dir %s\n" % execPath

gallery.main(utils.ingestData(execPath))

