#! /usr/bin/env python
# -*-coding: utf8-*-
# file: slideShow


import os
import sys

print "********* Required Python Version:  2.7.1 *******\n"  
print "You are using Python Version: %s\n" % sys.version

MODULES_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), "python")
sys.path.insert(0, MODULES_PATH)

import utils
import slideShow
path = sys.argv[-1]

if os.path.isdir(path):
	# pick the argumet passed
	execPath = path
else:
	# pick the current working directory
	execPath = os.getcwd()

slideShow.main(utils.ingestData(execPath))


		
